/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// AzureUefiSettingsApplyConfiguration represents a declarative configuration of the AzureUefiSettings type for use
// with apply.
type AzureUefiSettingsApplyConfiguration struct {
	SecureBoot *string `json:"secureBoot,omitempty"`
	VTpm       *string `json:"vtpm,omitempty"`
}

// AzureUefiSettingsApplyConfiguration constructs a declarative configuration of the AzureUefiSettings type for use with
// apply.
func AzureUefiSettings() *AzureUefiSettingsApplyConfiguration {
	return &AzureUefiSettingsApplyConfiguration{}
}

// WithSecureBoot sets the SecureBoot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecureBoot field is set to the value of the last call.
func (b *AzureUefiSettingsApplyConfiguration) WithSecureBoot(value string) *AzureUefiSettingsApplyConfiguration {
	b.SecureBoot = &value
	return b
}

// WithVTpm sets the VTpm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VTpm field is set to the value of the last call.
func (b *AzureUefiSettingsApplyConfiguration) WithVTpm(value string) *AzureUefiSettingsApplyConfiguration {
	b.VTpm = &value
	return b
}
